### ISSUE TITLE
Clear seachbox on window hide

### ISSUE THREAD

**Issue by Chr1s70ph** [leokraft/QuickKey#45]
### Idea:
Option to toggle clearing the searchbox on each program start

### How it is now: 
The program only clears the when the user selected a character

### Proposed change:
New setting to toggle clearing the seachbox on each program start, so every time the program is opened, a clear searchbox is presented

**Comment by leokraft** [comment]
Lets just clear it every time the window closes.
This should be the simples version.
Also we probably don't want to leave any leftovers in the searchbox.
